### ISSUE TITLE
charge_limit_soc is always showing 0

### ISSUE THREAD

**Issue by pkuehnel** [tobiasehlert/teslamateapi#160]
Today I noticed, that charge_limit_soc is always showing 0 on all my cars. This has been working until I think two days ago.

**Comment by pkuehnel** [comment]
Next problem: plugged_in is always false

**Comment by pkuehnel** [comment]
Interesting: I restarted all TeslaMate Docker Containers and everything is fine again (Only restarting teslaMateAPI does not help). Could you please check if there are any issues if mosquito or teslamate is restarted? I do think so, because the issues came up when I updated my containers which resulted in restarting mosquito container

**Comment by pkuehnel** [comment]
Database container restarting could also be the issue. Got an update of this one, too.

**Comment by tobiasehlert** [comment]
Hi @pkuehnel,

Interesting case 🤔 
Well based on the integration from TeslaMateAPI side, we retrieve the latest possible value from the MQTT server. With that I mean, if the value was set like 5 hours ago, it's that last value that would be displayed.

If mosquitto is restarted/upgraded, that information might not be available. But that is in this case due to the mosquitto not storing that value on an upgrade and reading it back when it's online again. That is my only guess that could make that the status endpoint is not showing the correct value.

But in that case, the values should be populated from TeslaMate again when it's changed.. and then right away, the status endpoint should display the correct information.

Regarding database restart, the status page does not retrieve database content, so that should not be related.

**Comment by pkuehnel** [comment]
Hmm, interesting. Today I could not reproduce this behaviour. As soon as I woke up the car the data was updated.

**Comment by pkuehnel** [comment]
Today I have the same issue, TeslaMate is working and logging fine, but TeslaMateApi's values do not change. @tobiasehlert Are you interested in something like an Teamviewer session to observe this issue? If so, I could keep all containers running.
