### ISSUE TITLE
Suddenly - ""error":"Unable to load cars.""

### ISSUE THREAD

**Issue by chamsters** [tobiasehlert/teslamateapi#224]
Hi there!

As of 1 day ago I'm suddenly seeing the error `"error":"Unable to load cars."` as a result in the api call. 

Log shows
```log
[GIN] 2023/06/10 - 12:28:01 | 200 |       29.59µs |   192.168.1.136 | GET      "/api/v1/cars/1/status"
2023/06/10 12:28:36.963039 [error] TeslaMateAPICarsStatusV1 - (/api/v1/cars/2/status). Unable to load cars.; sql: Scan error on column index 1, name "name": converting NULL to string is unsupported
[GIN] 2023/06/10 - 12:28:36 | 200 |     715.882µs |   192.168.1.198 | GET      "/api/v1/cars/2/status"
2023/06/10 12:28:01.867631 [error] TeslaMateAPICarsStatusV1 - (/api/v1/cars/1/status). no info on this car ID; -
[GIN] 2023/06/10 - 12:27:01 | 200 |      30.612µs |   192.168.1.136 | GET      "/api/v1/cars/1/status"
2023/06/10 12:29:01.903511 [error] TeslaMateAPICarsStatusV1 - (/api/v1/cars/1/status). no info on this car ID; -
[GIN] 2023/06/10 - 12:29:01 | 200 |      30.542µs |   192.168.1.136 | GET      "/api/v1/cars/1/status"
```

I've tried a full reboot of the node and TeslaMate. TeslaMate data showing just fine. 

On v [1.16.1](https://github.com/tobiasehlert/teslamateapi/releases/tag/v1.16.1)

Any suggestions? Thanks!

**Comment by haexpo** [comment]
Same problem here.

Log shows:

teslamate_1     | 2023-06-11 11:45:27.618 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/*removed*/vehicle_data -> 408 (9104.728 ms)
teslamate_1     | 2023-06-11 11:45:27.619 [warning] TeslaApi.Error / %{"error" => "{\"error\": \"timeout\"}", "error_description" => "", "response" => nil}
teslamate_1     | 2023-06-11 11:45:27.619 car_id=2 [error] Error / :unknown
teslamate_1     | 2023-06-11 11:45:55.218 car_id=2 [info] Suspending logging

teslamateapi_1  | [GIN] 2023/06/10 - 19:01:21 | 200 |     1.97747ms | 192.168.XXX.XXX | GET      "/api/v1/cars/2/status"
teslamateapi_1  | 2023/06/10 19:01:25.294859 [error] TeslaMateAPICarsStatusV1 - (/api/v1/cars/2/status). Unable to load cars.; sql: Scan error on column index 1, name "name": converting NULL to string is unsupported

**Comment by tobiasehlert** [comment]
Hi @chamsters and @haexpo,

From the output of @haexpo to tell it seems to be TeslaMate that has issues itself since it gets a **408** response from the owner-api. TeslaMateApi uses the PostgreSQL database in which TeslaMate feed information like vehicle information and it would be there where the issue would be.

I've noticed the same thing on my setup and I encountered the same issue. After upgrading to the latest TeslaMate version (I use `edge`) it works fine. It's the commit https://github.com/adriankumpf/teslamate/commit/6af97bafc8cfee6bd22911a1014dae8dcbe1f419 that is required for TeslaMate to behave correct again, so we'll have to wait for a new release of TeslaMate to be published or you can temporarily switch to using `edge`.

Some issues/discussions on TeslaMate repo:
https://github.com/adriankumpf/teslamate/issues/3183
https://github.com/adriankumpf/teslamate/discussions/3234
https://github.com/adriankumpf/teslamate/discussions/3238

Same issue has also been reported in the tesla-api repo from timdoor:
https://github.com/timdorr/tesla-api/issues/728

I'll set the issue to close, but get back to me if you have any further questions.

Regards,
Tobias
