### ISSUE TITLE
proxy POST commands to Tesla owner API

### ISSUE THREAD

**Issue by LelandSindt** [tobiasehlert/teslamateapi#6]
Have you considered/would you consider endpoints that would relay requests to the car. 

I have had a service like this on my list of ToDo's for some time. Even writing what I will generously call a proof of concept/meets my needs solution (https://github.com/wizardlyEinstein/iftttGateway/blob/master/main.go#L85  note: this code is no longer functional) 

However, with the recent changes to Tesla's Auth scheme and managing tokens, and... life... you get the point.

Discovering this project made me realize that TeslaMate can manage the tokens... 

Does this interest you? Would you be open to Pull Requests adding operations like setting climate control, etc....

**Comment by tobiasehlert** [comment]
Hi @LelandSindt,

I've not considered any endpoints that would send commands towards the car. But just because I currently don't have the need myself for this, this doesn't mean that we can't add this 👍 

One thing that is required for this (if you ask me) is to provide a token to the API to validate that you are allowed to change settings in your car or open garage or what else you want.
Plus the default should be that the command possibility is disabled, so you need to manually enable it, in case that you want to use commands towards your car and not only retrieve data.

But yeah, that would be a nice addition of functionality and I am definitely open for pull requests!
What type of commands would you consider to be nice to have in this case?

**Comment by LelandSindt** [comment]
@tobiasehlert 

Wonderful, I agree that requiring a token and disabling all commands are good defaults. 

Reviewing the Tesla API and comparing it to what you have laid out, I think there may be a fairly simple pass through pattern for commands (POST) and possibly requests (GET).

`/cars/:CarID/command/:command` -> `/api/1/vehicles/:id/command/:command`
so... 
`/cars/1/command/honk_horn` -> `/api/1/vehicles/12345678901234567/command/honk_horn`

My inclination is to require a pass through allow list. 

pass-through.json
```
{"POST":["wake","command/honk_horn","command/window_control"]}
```

users could list paths to be allowed to pass thought to the Tesla API.

**Comment by LelandSindt** [comment]
...got my development environment into shape this morning, will see if I can mock something up in the next few days.

**Comment by LelandSindt** [comment]
https://github.com/tobiasehlert/teslamateapi/compare/main...gaussmeter:wip

**Comment by tobiasehlert** [comment]
@LelandSindt, awesome that you already got some code produced!

What do you think of this approach, that we add environmental vars where you can choose what you want to enable.
Here is a list of those that we would implement.. what you think?

- ENABLE_COMMANDS boolean (default: false) - this is to enable commands section
- COMMANDS_WAKE boolean (default: true) - only option enabled by default
- COMMANDS_ALERTS boolean (default: false)
- COMMANDS_HOMELINK boolean (default: false)
- COMMANDS_SENTRYMODE boolean (default: false)
- COMMANDS_DOORS boolean (default: false)
- COMMANDS_CHARGING boolean (default: false)
- COMMANDS_CLIMATE boolean (default: false)
- COMMANDS_SHARING boolean (default: false)
- COMMANDS_ALL boolean (default: false) - can be used to enable all commands above

**Comment by LelandSindt** [comment]
Using environment variables to [true|false] enable groups of commands has the advantage of being fairly simple understand and manage.  The disadvantage in my opinion is that it requires changes code changes to add new commands/endpoints. 

An allow list of commands _should_ enable the user to add new /command/endpoints if/when they are added by Tesla without any code change. 

... that said, we _could_ do both... 

```
if exists(allow_list.json)
  allow_list.add(allow_list.json)
  
if env(COMMANDS_WAKE)
  allow_list.add("/wake_up")

if env(COMMANDS_ALERT)
  allow_list.add("/command/flash_lights")
  allow_list.add("/command/honk_horn")  
```
for the GET to `/cars/:CarID/command` we can return `allow_list`

PUT vs POST... I would argue that PUT = create, POST = update/modify.... 

oh... you want to see `/wake_up` move to `/command/wake` --- again, any objection to both? or do you have strong feelings about keeping all commands under `/command/`

Honestly, I am lazy. If I can copy/paste (or better yet, just reference) documentation from https://tesla-api.timdorr.com/vehicle/commands noting the path difference.... one less thing to maintain.. :smile:

**Comment by LelandSindt** [comment]
Why the liberal use `log.Fatal(err)`, instead of returning `http.StatusInternalServerError` to the client?

**Comment by tobiasehlert** [comment]
@LelandSindt 

> Using environment variables to [true|false] enable groups of commands has the advantage of being fairly simple understand and manage. The disadvantage in my opinion is that it requires changes code changes to add new commands/endpoints.
> 
> An allow list of commands _should_ enable the user to add new /command/endpoints if/when they are added by Tesla without any code change.

Alright, I see a point why that would be a reasonable approach. It's not often that new commands are added (last was like end 2019 with V10) so I don't see that this should be an issue. The environmental approach is fairly easy, since TeslaMate is built on the same way.


> for the GET to `/cars/:CarID/command` we can return `allow_list`

I think that would be a good way to see, what environmental variables you got enabled, so you can see what endpoints you can use :)


> oh... you want to see `/wake_up` move to `/command/wake` --- again, any objection to both? or do you have strong feelings about keeping all commands under `/command/`

I didn't notice until you said, that the wake_up command isn't included under the command path. We could add an endpoint outside calling the same function to kick off a wake up call similar to for example preheating.


> Why the liberal use of `log.Fatal(err)`, instead of returning `http.StatusInternalServerError` to the client?

Well.. there is definitely no reason for me to do that. See it rather the way that I copy based a skeleton of Golang GIN code and went from there. So there are probably much better ways to do Golang code than I did.

You are very welcome to create a PR enhancing the repo and I am very happy for your engagement! :)

**Comment by LelandSindt** [comment]
@tobiasehlert 

I rebased off main, and added a check for the value of `X-Command-Token` as a method of authorization.

... I am not sold on this method for auth, if you have a better idea I am open to it.

I will start work on the allow list/environment variables next.

as for `log.Fatal()` it calls `os.Exit(1)`  https://golang.org/pkg/log/#Fatal  --- in my testing, this ends the process/returns the command prompt. :man_shrugging: 

I am glad to help and appreciate the feedback, I will open a PR once I am closer to complete.. (I have a bad habit of using `commit --amend` and `force push` early in development, makes a mess of PRs..) :smile:

**Comment by LelandSindt** [comment]
@tobiasehlert 

I think my fork covers everything that we have talked about... However, some of the code is a little W.E.T... and its a little silly to walk `COMMANDS_*` and load `COMMANDS_ALLOWLIST` on _every_ request... 

Do you have any preference for how/where the config load should take place?

**Comment by tobiasehlert** [comment]
Hi @LelandSindt,

Great work so far!
There are some things that I would like to adjust a little.. could you create a PR to the [feature-commands](/tobiasehlert/teslamateapi/tree/feature-commands) branch? :)

Things I am spontaneous thinking of when checking your code so far:

- [ ] Authentication layer should use some [middleware](https://github.com/gin-gonic/gin#using-middleware) in gin-gonic instead of some new header.
JWT is too overkill, since we probably only have one user per API. What about [authorization bearer](https://stackoverflow.com/a/56175121) way?
- [ ] Authentication should only apply for the POST requests (so move some parts to webserver.go)
- [ ] `TeslaMateAPICarsCommand` should be `TeslaMateAPICarsCommandV1`, so we can version things later on.
- [ ] `getAllowList` should be different.. we should either use the `COMMANDS_ALLOWLIST` method **or** individual env vars.
There could be confusion when using both at the same time and we want to minimize confusion.
- [ ] `getEnvAsBool("COMMANDS_ALL", false)` is called a lot, so better call it once and use some var inside the if-statements?

So make a PR on your existing work to the [feature-commands](/tobiasehlert/teslamateapi/tree/feature-commands) branch and I can add some changes :)

Regards,
Tobias

**Comment by LelandSindt** [comment]
@tobiasehlert 

Thank you, again I am glad to contribute. 

I have addressed the following...

- [ x]  `TeslaMateAPICarsCommand` should be `TeslaMateAPICarsCommandV1`, so we can version things later on.
- [ x]  `getAllowList` should be different.. we should either use the `COMMANDS_ALLOWLIST` method or individual env vars.
- [ x] There could be confusion when using both at the same time and we want to minimize confusion.
- [ x]  `getEnvAsBool("COMMANDS_ALL", false)` is called a lot, so better call it once and use some var inside the if-statements?

and created a PR..

**Comment by LelandSindt** [comment]
Did  you have a specific middleware in mind?

I stared looking at this tonight: https://github.com/pjebs/restgate --- still not sure I grok how to implement it.

**Comment by tobiasehlert** [comment]
Hi @LelandSindt

I've added couple of new code now.

Made a AuthSupport and CommandSupport file containing a couple of functions.
Authentication can be done by adding `?token=<32+ token>` at the end of the URI
Also added (but yet in comments) support for `Authorization: Bearer <token>` 

I'm not sure if that is a good implementation.. it basically accepts same token either by parameter in URI or as header.

COMMANDS_ALLOWLIST part is also uncommented, since I have no time to validate it at the moment. I'll look into it tomorrow or later :)

And yeah.. some more few things.. you will probably see :)

**Comment by LelandSindt** [comment]
@tobiasehlert 

This feature is certainly shaping up!

I have concerns about accepting the token on the query string... 

`[GIN] 2021/03/11 - 19:05:46 | 200 |  2.801780762s |       127.0.0.1 | POST     "/api/v1/cars/1/command/honk_horn?token=UjdTVsAMdG02H5kzJ21hGRNmvzK0cKXM8f21jjBxLq0rDL1yt26o7ykmpB8UnmWK`

Compromised logs leak secrets... 

I will review in more detail and work to validate the `Authorization: Bearer <token>` option.

**Comment by LelandSindt** [comment]
I enabled, and walked through the `Authorization: Bearer <token>` option, it worked and seems generally sound to me.

That said, I did _a little_ research into what an `Bearer` token is... 

https://swagger.io/docs/specification/authentication/bearer-authentication/
https://developer.mozilla.org/en-US/docs/Web/HTTP/Authentication#authentication_schemes
https://tools.ietf.org/html/rfc6750

The way I read it  `Authorization: Bearer <token>` is a part of the OAuth standard, which we are not implementing here.

This is why I "made up" the `X-Command-Token` header... :shrug: 

your thoughts?

**Comment by tobiasehlert** [comment]
> I have concerns about accepting the token on the query string...
> 
> `[GIN] 2021/03/11 - 19:05:46 | 200 | 2.801780762s | 127.0.0.1 | POST "/api/v1/cars/1/command/honk_horn?token=UjdTVsAMdG02H5kzJ21hGRNmvzK0cKXM8f21jjBxLq0rDL1yt26o7ykmpB8UnmWK`
> 
> Compromised logs leak secrets...

Definitely.. and that's why I'm not super happy about that either.
We can add a note in the documentation that the token will be logged and can be a security risk and you should rather use the Authorization method.


> The way I read it `Authorization: Bearer <token>` is a part of the OAuth standard, which we are not implementing here.

No, it's not an OAuth only method.. I had the same concerns and I googled around a lot and found that the [learn postman page](https://learning.postman.com/docs/sending-requests/authorization/#bearer-token) talking about bearer tokens says _such as a JSON Web Token (JWT)_. So based on that I think it's totally up to yourself to use it that way.

I do also consume the [Tibber API](https://developer.tibber.com/docs/guides/calling-api) as well and they use the same method with `Authorization: Bearer <token>` where you place your personal token that you received in that field.

So.. my conclusion is that `Authorization: Bearer <token>` should be the best way and that you _can_ use ?token=<token> in case you want as well, but need to understand that the logs including token can leak.

What you think @LelandSindt? :)

**Comment by tobiasehlert** [comment]
Pushed my changes to the [feature-commands](/tobiasehlert/teslamateapi/tree/feature-commands) branch now.. take a look if you think it looks good @LelandSindt :)

**Comment by tobiasehlert** [comment]
@LelandSindt merges your PR and adjusted the example file a little.

Now what's left to do is to get the command allow_list part working as well (or well.. it works.. but is commented out).
https://github.com/tobiasehlert/teslamateapi/blob/feature-commands/src/CommandSupport.go#L129

I think I can have that fixed until later today and then you can test yourself later if everything looks as you like. :)
If so, we should be ready to merge it into the main branch and release a new version

**Comment by tobiasehlert** [comment]
I'll test this today and hopefully we can merge everything this evening :)

**Comment by tobiasehlert** [comment]
@LelandSindt, I think I'm happy with how it turned out.
I haven't tested the allow_list part, since I use environmental variables only, but please confirm that it works as you expect it to.

I'll create a PR in the meantime and if you give a thumbs up, I'll merge it all.

**Comment by LelandSindt** [comment]
:+1:
