### ISSUE TITLE
It is suggested to add options。

### ISSUE THREAD

**Issue by lylus** [tobiasehlert/teslamateapi#70]
It is recommended that all endpoints can choose to enable api_token authentication, because when the service is built on an external network and needs to verify the teslamate user and password, api_token using the instruction endpoint will need double verification. When I use the shortcut app of Apple IOS, the verification is a little cumbersome. If api_token authentication is enabled for all endpoints, I don't need to set the password of teslamate user to access.

**Comment by lylus** [comment]
Bug:

traefik:
Authorization:Basic 6YWFjY3p6e

teslamateapi:
Authorization: Bearer znFsbtg3dAewg342Jak1z1Y

Authorization 

The same name conflicts and cannot be verified at the same time.

**Comment by LelandSindt** [comment]
We could consider adding `API_TOKEN_DISABLE` with a default of `false`. `true` should throw a warning in the logs and skip the `Authorization: Bearer ` check...

**Comment by lylus** [comment]
Can I find a solution in this link?

[(https://stackoverflow.com/questions/22229996/basic-http-and-bearer-token-authentication)]

You can pass the token under another name. Because you are handling the authorization from your Application. So you can easily use this flexibility for this special purpose.

curl -i http://dev.myapp.com/api/users \
  -H "Authorization: Basic Ym9zY236Ym9zY28=" \
  -H "Application-Authorization: mytoken123"
Notice I have changed the header into Application-Authorization. So from your application catch the token under that header and process what you need to do.

Another thing you can do is, to pass the token through the POST parameters and grab the parameter's value from the Server side. For example passing token with curl post parameter:

-d "auth-token=mytoken123"

**Comment by tobiasehlert** [comment]
Hi @lylus,

Hope the PR from @LelandSindt (thanks!) helps you to resolve your issue.

I don't see that changing the name of the Authorization header would be the best way forward, since that can break other users setup. So the implementation of a disable of token check should fit much better. Since you rely on Traefik to do the authorization, this should be just fine.

If you want to test to code, run the docker image tag `main` to be able to test it. Else I will merge it into `latest `probably during today evening :)

Regards,
Tobias
